### ISSUE TITLE
PUT /clubs/{id}/users/{userId}

### ISSUE THREAD

**Issue by Yoonhwi** [joinus-devs/backend#14]
해당 요청으로 user role 을 pending에서 member로 update해주는 과정에서
400Error를 반환합니다.
![image](https://github.com/joinus-devs/backend/assets/123847036/0835d391-e928-4852-b741-8e2d4a2a0534)

![image](https://github.com/joinus-devs/backend/assets/123847036/f35ad1bd-ce43-474c-b448-78e6b0640a72)

**Comment by Lee-Minhoon** [comment]
고쳤습니다.
