### ISSUE TITLE
POST /auth/signup/social

### ISSUE THREAD

**Issue by rlawogns123** [joinus-devs/backend#15]
![컹s](https://github.com/joinus-devs/backend/assets/73879034/88e42720-d5c6-4243-8625-cd098f578000)
![컹s2](https://github.com/joinus-devs/backend/assets/73879034/014a0ae3-053b-4722-b07b-e43b0fe67d25)

소셜 회원가입 시도를 하면 500 error를 반환하네요

**Comment by Lee-Minhoon** [comment]
원래, profile 필드가 들어와야 하는데, 없어서 그렇습니다. profile 필드 없이 회원가입 가능하도록 수정했습니다.
